trigger:
  - develop
  
resources:
  - repo: self
  
variables:
    azureSubscription: "svc-conn-trace-cms-azure-portal"
    containerRegistry: "acreausdev.azurecr.io"
    env: "dev"
    dockerComposeFile: "./docker-compose/docker-compose.yml"
    imageRepositoryWeb: "trace-cms-web"
    keyVaultName:  "keyvault-eaus-dev"
    imageTag: $(Build.BuildNumber)
    vmImageName: "ubuntu-latest"
  
stages:
  - stage: Build
    displayName: Build image
    jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: DockerCompose@0
        displayName: "Docker compose build"
        inputs:
          action: "Build services"
          dockerComposeFile: $(dockerComposeFile)
          containerregistrytype: "Azure Container Registry"
          azureSubscription: $(azureSubscription)
          azureContainerRegistry: $(containerRegistry)
          additionalImageTags: $(imageTag)
          dockerComposeCommand: build
      - task: DockerCompose@0
        displayName: "Push image"
        inputs:
          action: "Push services"
          dockerComposeFile: $(dockerComposeFile)
          containerregistrytype: "Azure Container Registry"
          azureSubscription: $(azureSubscription)
          azureContainerRegistry: $(containerRegistry)
          additionalImageTags: $(imageTag)
          dockerComposeCommand: push
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: $(azureSubscription)
          KeyVaultName: $(keyVaultName)
          SecretsFilter: "*"
          RunAsPreJob: true
  