# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - appsvc-eaus-web-dev

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acreausdev.azurecr.io/
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Get current date
      id: getdate
      run: | 
        echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      
    - name: Build and push container image to registry
      id: build-and-push-image
      working-directory: ./
      env: 
        AZ_REGISTRY: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        IMAGE_TAG: tracecms-web:${{ steps.getdate.outputs.date }}.${{ github.run_attempt }}
      run: |
        docker build -t $AZ_REGISTRY/$IMAGE_TAG -f ./configurations/docker/api/Dockerfile .
        docker push $AZ_REGISTRY/$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'appsvc-eaus-web-dev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_APP_PROFILE }}
        images: acreausdev.azurecr.io/tracecms-web:${{ steps.getdate.outputs.date }}.${{ github.run_attempt }}
